/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;
import backend.Hospital;
import backend.Sistema;
import backend.Serializacao;

/**
 *
 * @author ssoar
 */
public class FichaHospital extends javax.swing.JFrame {
    private Sistema sistema;
    private Serializacao bd;
    /* int varHosp; */

    /**
     * Creates new form Ficha_Hospital_G
     * @param sistema
     * @param bd
     */
    public FichaHospital(Sistema sistema, Serializacao bd) {
        initComponents();
        this.sistema=sistema;
        this.bd = bd;
        /*this.varHosp = varHosp;
        Hospital hosp = sistema.getListaHospital().getListaHospital().get(varHosp);*/
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btEnfermaria = new javax.swing.JButton();
        btDoentes = new javax.swing.JButton();
        btProfissionais = new javax.swing.JButton();
        btEquipamentos = new javax.swing.JButton();
        txtLocalidade = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        imgRetroceder = new javax.swing.JLabel();
        imgHome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(374, 348));
        setMinimumSize(new java.awt.Dimension(374, 348));
        setUndecorated(true);
        setSize(new java.awt.Dimension(374, 348));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 50, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Localidade :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 90, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("Ficha Hospital");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 10, 120, 20);

        btEnfermaria.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btEnfermaria.setText("Lista Enfermarias");
        btEnfermaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnfermariaActionPerformed(evt);
            }
        });
        getContentPane().add(btEnfermaria);
        btEnfermaria.setBounds(20, 160, 180, 29);

        btDoentes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btDoentes.setText("Lista de Doentes");
        btDoentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoentesActionPerformed(evt);
            }
        });
        getContentPane().add(btDoentes);
        btDoentes.setBounds(20, 200, 180, 29);

        btProfissionais.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btProfissionais.setText("Lista de Profissionais");
        btProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfissionaisActionPerformed(evt);
            }
        });
        getContentPane().add(btProfissionais);
        btProfissionais.setBounds(20, 240, 180, 29);

        btEquipamentos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btEquipamentos.setText("Lista de Equipamentos");
        btEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEquipamentosActionPerformed(evt);
            }
        });
        getContentPane().add(btEquipamentos);
        btEquipamentos.setBounds(20, 280, 180, 29);

        txtLocalidade.setEnabled(false);
        getContentPane().add(txtLocalidade);
        txtLocalidade.setBounds(120, 100, 130, 30);

        txtNome.setEnabled(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(120, 50, 130, 30);

        imgRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/undo-button2.png"))); // NOI18N
        imgRetroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgRetrocederMouseClicked(evt);
            }
        });
        getContentPane().add(imgRetroceder);
        imgRetroceder.setBounds(290, 10, 24, 30);

        imgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sydney-opera-house.png"))); // NOI18N
        imgHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHomeMouseClicked(evt);
            }
        });
        getContentPane().add(imgHome);
        imgHome.setBounds(330, 10, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pag_ini_3.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-4, 0, 640, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEnfermariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnfermariaActionPerformed
        // TODO add your handling code here:
        hide();
        ListaEnfermarias listaEnfermarias = new ListaEnfermarias(sistema,bd);
        listaEnfermarias.setLocationRelativeTo(null);
        listaEnfermarias.setVisible(true);
    }//GEN-LAST:event_btEnfermariaActionPerformed

    private void btDoentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoentesActionPerformed
        // TODO add your handling code here:
        hide();
        ListaDoentes listaDoentes = new ListaDoentes(sistema,bd);
        listaDoentes.setLocationRelativeTo(null);
        listaDoentes.setVisible(true);
    }//GEN-LAST:event_btDoentesActionPerformed

    private void btProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfissionaisActionPerformed
        // TODO add your handling code here:
        hide();
        ListaProfissionalSaude listaProfissionalSaude = new ListaProfissionalSaude(sistema,bd);
        listaProfissionalSaude.setLocationRelativeTo(null);
        listaProfissionalSaude.setVisible(true);
    }//GEN-LAST:event_btProfissionaisActionPerformed

    private void btEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEquipamentosActionPerformed
        // TODO add your handling code here:
        hide();
        ListaEquipamentos listaEquipamentos = new ListaEquipamentos(sistema,bd);
        listaEquipamentos.setLocationRelativeTo(null);
        listaEquipamentos.setVisible(true);
    }//GEN-LAST:event_btEquipamentosActionPerformed

    private void imgHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHomeMouseClicked
        // TODO add your handling code here:
        dispose();
        PaginaInicialUtilizador paginaInicialUtilizador = new PaginaInicialUtilizador(sistema,bd);
        paginaInicialUtilizador.setLocationRelativeTo(null);
        paginaInicialUtilizador.setVisible(true);
    }//GEN-LAST:event_imgHomeMouseClicked

    private void imgRetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRetrocederMouseClicked
        // TODO add your handling code here:
        dispose();
        ListaHospitais listaHospitais = new ListaHospitais(sistema,bd);
        listaHospitais.setLocationRelativeTo(null);
        listaHospitais.setVisible(true);
    }//GEN-LAST:event_imgRetrocederMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Ficha_Hospital_G().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDoentes;
    private javax.swing.JButton btEnfermaria;
    private javax.swing.JButton btEquipamentos;
    private javax.swing.JButton btProfissionais;
    private javax.swing.JLabel imgHome;
    private javax.swing.JLabel imgRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtLocalidade;
    public javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
