/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Medico;
import backend.Sistema;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ssoar
 */
public class LoginForm extends javax.swing.JFrame {

    private Sistema sis;
    /**
     * Creates new form NewJFrame
     * @param s
     */
    public LoginForm(Sistema s) {
        initComponents();
        
        this.setTitle("Login");
        this.setIconImage(new ImageIcon("./src/anexos/tasks-blue-icon-14527.png").getImage());
        // FIXME Este icon vem daqui http://downloadicons.net/tasks-blue-icon-14527
        
        sis = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 180, 50, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 230, 50, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 180, 120, 30);

        btEntrar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar);
        btEntrar.setBounds(50, 290, 90, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(140, 230, 120, 30);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 290, 90, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_medico3.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 720, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        // TODO add your handling code here:
        
         String nome = txtNome.getText();
         String password = new String(txtSenha.getPassword());
         
         if(nome.equals("admin") && password.equals("admin"))
         {   
            if (!(nome.length() <= 0 || password.length() <= 0)) {
                Medico user = new Medico(nome, password);

           // Verificar se o nome existe
                if (sis.getListaMedico().existe(user)) {
                    // Neste caso existe um utilizador com o mesmo nome
                    // Confirmar se a palavra passe é igual
                    int pos = sis.getListaMedico().posicao(user); // Se isto devolver -1 então
                    // não existe um utilizador com este nome

                    user = sis.getListaMedico().devolveUtilizador(pos);

                    if (user.getPassword().equals(password)) {
                        // Caso em que está tudo certo e o login é efetuado com sucesso

                        PaginaAdministrador janelaPA = new PaginaAdministrador(sis);
                        janelaPA.setLocationRelativeTo(null); //centrar
                        janelaPA.setVisible(true);
                        sis.setUtilizadorLogin(user);
                        this.dispose();

                    } else {
                   // Caso em que a palavra passe está errada
                   JOptionPane.showMessageDialog(null, "Dados incorretos", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
               // Caso em que não existe o nome
               JOptionPane.showMessageDialog(null, "Dados incorretos", "ERRO", JOptionPane.ERROR_MESSAGE);
           }

           } else {
               JOptionPane.showMessageDialog(null, "Preencha os campos corretamente", "ERRO", JOptionPane.ERROR_MESSAGE);
           }
       }
            else 
            {
                 if (!(nome.length() <= 0 || password.length() <= 0)) {
                    Medico user = new Medico(nome, password);

                     // Verificar se o nome existe
                     if (sis.getListaMedico().existe(user)) {
                        // Neste caso existe um utilizador com o mesmo nome
                        // Confirmar se a palavra passe é igual
                        int pos = sis.getListaMedico().posicao(user); // Se isto devolver -1 então
                        // não existe um utilizador com este nome

                        user = sis.getListaMedico().devolveUtilizador(pos);

                            if (user.getPassword().equals(password)) {
                                // Caso em que está tudo certo e o login é efetuado com sucesso

                                PaginaInicialUtilizador janelaPIU = new PaginaInicialUtilizador(sis);
                                janelaPIU.setLocationRelativeTo(null); //centrar
                                janelaPIU.setVisible(true);
                                sis.setUtilizadorLogin(user);
                                this.dispose();

                            } else {
                            // Caso em que a palavra passe está errada
                            JOptionPane.showMessageDialog(null, "Dados incorretos", "ERRO", JOptionPane.ERROR_MESSAGE);
                            }
                    } else {
                        // Caso em que não existe o nome
                        JOptionPane.showMessageDialog(null, "Dados incorretos", "ERRO", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Preencha os campos corretamente", "ERRO", JOptionPane.ERROR_MESSAGE);

                }
       }  
    }//GEN-LAST:event_btEntrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
