/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;
import backend.Doente;
import javax.swing.table.DefaultTableModel;
import backend.Sistema;
import backend.Serializacao;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ssoar
 */
public class PaginaDoentesGenerica extends javax.swing.JFrame {
    DefaultTableModel model; 
    private Sistema sistema;
    private Serializacao bd;
    private int indiceHospital;
    private int indiceEnfermaria;
    private int indiceMedico;
    /**
     * 
     * @param sistema
     * @param bd 
     */
    public PaginaDoentesGenerica(Sistema sistema,Serializacao bd) {
        initComponents();
        model = (DefaultTableModel) tableDoente.getModel();
        this.sistema=sistema;
        this.bd = bd;
        
        carregarTabelaDoenteGen();
        
         //ordena tabela de forma ascedente e descendente
        tableDoente.setRowSorter(new TableRowSorter(model));
    }
    
    public void carregarTabelaDoenteGen()
    {

        model.setRowCount(0);

       /* ArrayList<Hospital> hospital = sistema.getListaHospital().getListaHospital();
        ArrayList<Enfermaria> enfermaria = sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria(); 
        ArrayList<Medico> medico = sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria().get(indiceEnfermaria).getListaMedico().getListaMedico();
        ArrayList<Doente> doente = sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria().get(indiceEnfermaria).getListaMedico().getListaMedico().get(indiceMedico).getListaDoente().getListaDoente();*/

        for (indiceHospital = 0; indiceHospital < sistema.getListaHospital().getListaHospital().size(); indiceHospital++) {

            for (indiceEnfermaria = 0; indiceEnfermaria < sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria().size(); indiceEnfermaria++) {

                for (indiceMedico = 0 ; indiceMedico < sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria().get(indiceEnfermaria).getListaMedico().getListaMedico().size() ; indiceMedico++) {

                    for (int indiceDoente = 0; indiceDoente <  sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria().get(indiceEnfermaria).getListaMedico().getListaMedico().get(indiceMedico).getListaDoente().getListaDoente().size(); indiceDoente++) {

                        Doente doente = sistema.getListaHospital().getListaHospital().get(indiceHospital).getListaEnfermaria().getListaEnfermaria().get(indiceEnfermaria).getListaMedico().getListaMedico().get(indiceMedico).getListaDoente().getListaDoente().get(indiceDoente);
                        
                        //compara o utilizador que está associado ao doente com o que está logado no preciso momento
                        if (doente.getUtiLigado().equals(sistema.getUtilizadorLigado())) {
                            model.addRow(new Object[]{doente.getIdDoente(), doente.getNomeDoente(), doente.getDataNasc(), doente.getLocalidade(), doente.getNCama(), doente.getGravidade(), doente.getDataEntrada(), doente.getDataSaida()});
                        }
                    }
                }
            }
        }
        tableDoente.setModel(model);
              
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDoente = new javax.swing.JTable();
        imgHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboGravidade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(805, 480));
        setUndecorated(true);
        setSize(new java.awt.Dimension(804, 363));
        getContentPane().setLayout(null);

        tableDoente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Data Nascimento", "Localidade", "Cama", "Gravidade", "Data Entrada", "Data Saída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDoente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableDoente.setEnabled(false);
        jScrollPane1.setViewportView(tableDoente);
        if (tableDoente.getColumnModel().getColumnCount() > 0) {
            tableDoente.getColumnModel().getColumn(0).setResizable(false);
            tableDoente.getColumnModel().getColumn(1).setResizable(false);
            tableDoente.getColumnModel().getColumn(2).setResizable(false);
            tableDoente.getColumnModel().getColumn(3).setResizable(false);
            tableDoente.getColumnModel().getColumn(4).setResizable(false);
            tableDoente.getColumnModel().getColumn(5).setResizable(false);
            tableDoente.getColumnModel().getColumn(6).setResizable(false);
            tableDoente.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 750, 250);

        imgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sydney-opera-house.png"))); // NOI18N
        imgHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHomeMouseClicked(evt);
            }
        });
        getContentPane().add(imgHome);
        imgHome.setBounds(750, 50, 30, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setText("Lista de Doentes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 10, 160, 30);

        ComboGravidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gravidade", "Moderado", "Grave", "Muito Grave" }));
        ComboGravidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboGravidadeItemStateChanged(evt);
            }
        });
        getContentPane().add(ComboGravidade);
        ComboGravidade.setBounds(650, 400, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundPRI.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -220, 1700, 1100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imgHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHomeMouseClicked
        // TODO add your handling code here:
        dispose();
        PaginaInicialUtilizador paginaInicialUtilizador = new PaginaInicialUtilizador(sistema,bd);
        paginaInicialUtilizador.setLocationRelativeTo(null);
        paginaInicialUtilizador.setVisible(true);
    }//GEN-LAST:event_imgHomeMouseClicked
   
    private void filtrar (String gravidade){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tableDoente.setRowSorter(tr);
        if (!"Gravidade".equals(gravidade)){
            tr.setRowFilter(RowFilter.regexFilter(gravidade));
        }else{
            tableDoente.setRowSorter(tr);
        }
   }
   
    
    
    private void ComboGravidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboGravidadeItemStateChanged
        // TODO add your handling code here:
        String gravidade = ComboGravidade.getSelectedItem().toString();
        
        filtrar(gravidade);
    }//GEN-LAST:event_ComboGravidadeItemStateChanged

    
     
    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaDoentesGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaDoentesGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaDoentesGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaDoentesGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListaDoentesGenerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboGravidade;
    private javax.swing.JLabel imgHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDoente;
    // End of variables declaration//GEN-END:variables

}
