/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Serializacao;
import backend.Sistema;
import backend.Administrador;
import javax.swing.JOptionPane;
/**
 *
 * @author ssoar
 */
public class PaginaInicial extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao bd;
    
    public PaginaInicial(Sistema sistema, Serializacao bd) 
    {
        initComponents();
        
        this.sistema = sistema;
        this.bd = bd;
        
        //Força a maximização da janela
        //this.setExtendedState(PaginaInicial.MAXIMIZED_BOTH);    
        
        //Mostra a centralização da janela
        this.setLocationRelativeTo(null);
        
        //O processo de fecho da janela será controlado pelo programa
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        //Apenas mostra o menu de administração se o utilizador for um administrador
        imgAdmin.setVisible(sistema.getUtilizadorLigado() instanceof Administrador);
        txtAdmin.setVisible(sistema.getUtilizadorLigado() instanceof Administrador);
        
        //Apenas mostra o menu de utilizador se o de administração estiver oculto
        imgMedico.setVisible(!imgAdmin.isVisible());
        txtUtilizador.setVisible(!imgAdmin.isVisible());
    }
    
    private void guardarAlteracoes() {
        bd.gravaSistema(sistema);
    }
    
    
    private void terminar() {        
       if (JOptionPane.showConfirmDialog(null, 
               "Deseja realmente terminar o programa?", 
               "Terminar", 
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
           guardarAlteracoes();
           sistema.terminar();
       }
   }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgMedico = new javax.swing.JLabel();
        imgAdmin = new javax.swing.JLabel();
        txtUtilizador = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(348, 375));
        setMinimumSize(new java.awt.Dimension(348, 375));
        setSize(new java.awt.Dimension(348, 375));
        getContentPane().setLayout(null);

        imgMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/doctor (1).png"))); // NOI18N
        imgMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMedicoMouseClicked(evt);
            }
        });
        getContentPane().add(imgMedico);
        imgMedico.setBounds(210, 10, 120, 130);

        imgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/support (1).png"))); // NOI18N
        imgAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAdminMouseClicked(evt);
            }
        });
        getContentPane().add(imgAdmin);
        imgAdmin.setBounds(210, 200, 128, 130);

        txtUtilizador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtUtilizador.setText("Utilizador");
        getContentPane().add(txtUtilizador);
        txtUtilizador.setBounds(240, 150, 70, 20);

        txtAdmin.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtAdmin.setText("Administrador");
        getContentPane().add(txtAdmin);
        txtAdmin.setBounds(230, 340, 100, 20);

        imgSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSairMouseClicked(evt);
            }
        });
        getContentPane().add(imgSair);
        imgSair.setBounds(20, 320, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pagini.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -10, 630, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAdminMouseClicked
        // TODO add your handling code here:
        PaginaAdministrador paginaAdministrador = new PaginaAdministrador(sistema, bd);
        paginaAdministrador.setVisible(true);  
        
    }//GEN-LAST:event_imgAdminMouseClicked

    private void imgMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMedicoMouseClicked
        // TODO add your handling code here:
        PaginaInicialUtilizador paginaInicialUtilizador = new PaginaInicialUtilizador(sistema, bd);
        paginaInicialUtilizador.setVisible(true);
        
    }//GEN-LAST:event_imgMedicoMouseClicked

    private void imgSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_imgSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PaginaIni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgAdmin;
    private javax.swing.JLabel imgMedico;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtAdmin;
    private javax.swing.JLabel txtUtilizador;
    // End of variables declaration//GEN-END:variables
}
