/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Sistema;
import javax.swing.JOptionPane;
import backend.Serializacao;
import backend.Administrador;
import backend.RegistoAcesso;

/**
 *
 * @author ssoar
 */
public class PaginaInicialUtilizador extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicialUtilizador
     */
    private Sistema sistema;
    private Serializacao bd;
    
    public PaginaInicialUtilizador(Sistema sistema, Serializacao bd) {
        initComponents();
        
        this.sistema = sistema;
        this.bd = bd;
        
        //Força a maximização da janela
        //this.setExtendedState(PaginaIni.MAXIMIZED_BOTH);    
        
        //O processo de fecho da janela será controlado pelo programa
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
    }
    
    private void guardarAlteracoes() {
        bd.gravaSistema(sistema);
    }
    
    
    private void terminar() {        
        if (JOptionPane.showConfirmDialog(null, 
                "Deseja realmente terminar o programa?", 
                "Terminar", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            guardarAlteracoes();
            sistema.terminar();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btListaHospital = new javax.swing.JButton();
        btListaEnfermarias = new javax.swing.JButton();
        imgPerfil = new javax.swing.JLabel();
        imgSair = new javax.swing.JLabel();
        btListaDoentes = new javax.swing.JButton();
        btListaEquipamentos = new javax.swing.JButton();
        btListaProfissionais = new javax.swing.JButton();
        imgGuardar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(444, 320));
        setUndecorated(true);
        setSize(new java.awt.Dimension(444, 320));
        getContentPane().setLayout(null);

        btListaHospital.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btListaHospital.setText("Lista de Hospitais");
        btListaHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(btListaHospital);
        btListaHospital.setBounds(10, 60, 180, 29);

        btListaEnfermarias.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btListaEnfermarias.setText("Lista de Enfermarias");
        btListaEnfermarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaEnfermariasActionPerformed(evt);
            }
        });
        getContentPane().add(btListaEnfermarias);
        btListaEnfermarias.setBounds(10, 260, 180, 30);

        imgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfilIcon.png"))); // NOI18N
        imgPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPerfilMouseClicked(evt);
            }
        });
        getContentPane().add(imgPerfil);
        imgPerfil.setBounds(20, 10, 30, 30);

        imgSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout.png"))); // NOI18N
        imgSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgSairMouseClicked(evt);
            }
        });
        getContentPane().add(imgSair);
        imgSair.setBounds(60, 10, 24, 30);

        btListaDoentes.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btListaDoentes.setText("Lista de Doentes");
        btListaDoentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaDoentesActionPerformed(evt);
            }
        });
        getContentPane().add(btListaDoentes);
        btListaDoentes.setBounds(10, 110, 180, 30);

        btListaEquipamentos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btListaEquipamentos.setText("Lista de Equipamentos");
        btListaEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaEquipamentosActionPerformed(evt);
            }
        });
        getContentPane().add(btListaEquipamentos);
        btListaEquipamentos.setBounds(10, 160, 180, 30);

        btListaProfissionais.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btListaProfissionais.setText("Lista de Profissionais");
        btListaProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaProfissionaisActionPerformed(evt);
            }
        });
        getContentPane().add(btListaProfissionais);
        btListaProfissionais.setBounds(10, 210, 180, 30);

        imgGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        imgGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(imgGuardar);
        imgGuardar.setBounds(100, 10, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dashboard (1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pag_ini_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-100, 0, 620, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btListaHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaHospitalActionPerformed
        // TODO add your handling code here:
        dispose();
        ListaHospitais p = new ListaHospitais(sistema,bd);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btListaHospitalActionPerformed

    private void btListaEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaEquipamentosActionPerformed
        // TODO add your handling code here:
        dispose();
        ListaEquipamentosGenerica p = new ListaEquipamentosGenerica(sistema,bd);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btListaEquipamentosActionPerformed

    private void imgGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgGuardarMouseClicked
        // TODO add your handling code here:
        guardarAlteracoes();
        JOptionPane.showMessageDialog(this, "Alterações guardadas.");
    }//GEN-LAST:event_imgGuardarMouseClicked

    private void imgPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPerfilMouseClicked
        // TODO add your handling code here:
        Perfil perfil = new Perfil(sistema, sistema.getUtilizadorLigado(), null);
        perfil.setVisible(true);
        
    }//GEN-LAST:event_imgPerfilMouseClicked

    private void imgSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgSairMouseClicked
        // TODO add your handling code here:
        terminar();
    }//GEN-LAST:event_imgSairMouseClicked

    private void btListaDoentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaDoentesActionPerformed
        // TODO add your handling code here:
        dispose();
        ListaDoentesGenerica p = new ListaDoentesGenerica(sistema,bd);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btListaDoentesActionPerformed

    private void btListaProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaProfissionaisActionPerformed
        // TODO add your handling code here:
        
        ListaProfissionaisGenerica p = new ListaProfissionaisGenerica(sistema,bd);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        this.close();
    }//GEN-LAST:event_btListaProfissionaisActionPerformed

    private void btListaEnfermariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaEnfermariasActionPerformed
        // TODO add your handling code here:
        dispose();
        ListaEnfermariasGenerica p = new ListaEnfermariasGenerica(sistema,bd);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btListaEnfermariasActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
        Dashboard d = new Dashboard(sistema,bd);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicialUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PaginaInicialUtilizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListaDoentes;
    private javax.swing.JButton btListaEnfermarias;
    private javax.swing.JButton btListaEquipamentos;
    private javax.swing.JButton btListaHospital;
    private javax.swing.JButton btListaProfissionais;
    private javax.swing.JLabel imgGuardar;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JLabel imgSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
