/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;
import backend.Equipamento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import backend.Sistema;
import backend.Serializacao;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ssoar
 */
public class PaginaEquipamentosGenerica extends javax.swing.JFrame {
     DefaultTableModel model; 
    private Sistema sistema;
    private Serializacao bd;

    /**
     * Creates new form ListaEquipamentosGenerica
     */
    public PaginaEquipamentosGenerica(Sistema sistema, Serializacao bd) {
        initComponents();
        
        model = (DefaultTableModel) tableEq.getModel();
        this.sistema=sistema;
        this.bd = bd;
        
        carregarTabelaGenerica();
    }
    
     public void carregarTabelaGenerica()
    {
        model.setRowCount(0);
         
         for(int i=0; i< sistema.getListaEquipamento().getListaEquipamento().size(); i++) {
             
            Equipamento equipamento = sistema.getListaEquipamento().getListaEquipamento().get(i);
            
            if (equipamento.getUtiLigado().equals(sistema.getUtilizadorLigado())) {
             model.addRow(new Object[]{equipamento.getIdEquip(), equipamento.getTipoEquipamento(), equipamento.getIndicacao(), equipamento.getDoente()});
            }
         }
         
          tableEq.setModel(model);
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEq = new javax.swing.JTable();
        imgHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboInd = new javax.swing.JComboBox<>();
        ComboTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(807, 358));
        setUndecorated(true);
        setSize(new java.awt.Dimension(807, 358));
        getContentPane().setLayout(null);

        tableEq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo", "Indicação", "Doente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEq);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 40, 690, 250);

        imgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sydney-opera-house.png"))); // NOI18N
        imgHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHomeMouseClicked(evt);
            }
        });
        getContentPane().add(imgHome);
        imgHome.setBounds(10, 10, 30, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lista de Equipamentos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 10, 190, 20);

        ComboInd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Tipo", "Desfibrilhador", "Ventilador", "Outro" }));
        ComboInd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboIndItemStateChanged(evt);
            }
        });
        ComboInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboIndActionPerformed(evt);
            }
        });
        getContentPane().add(ComboInd);
        ComboInd.setBounds(480, 310, 120, 30);

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Indicacao", "Livre", "Ocupado" }));
        ComboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTipoItemStateChanged(evt);
            }
        });
        getContentPane().add(ComboTipo);
        ComboTipo.setBounds(630, 310, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/G4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-170, -130, 1550, 830);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void imgHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHomeMouseClicked
        // TODO add your handling code here:
        dispose();
        PaginaInicialUtilizador paginaInicialUtilizador = new PaginaInicialUtilizador(sistema,bd);
        paginaInicialUtilizador.setLocationRelativeTo(null);
        paginaInicialUtilizador.setVisible(true);
    }//GEN-LAST:event_imgHomeMouseClicked

      private void filtrar (String tipo){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tableEq.setRowSorter(tr);
        if (!"Selecione o Tipo".equals(tipo)){
            tr.setRowFilter(RowFilter.regexFilter(tipo));
        }else{
            tableEq.setRowSorter(tr);
        }
        
    }
    
    private void filtrar2 (String Indicacao){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tableEq.setRowSorter(tr);
        if (!"Selecione Indicacao".equals(Indicacao)){
            tr.setRowFilter(RowFilter.regexFilter(Indicacao));
        }else{
            tableEq.setRowSorter(tr);
        }
        
    }
    
    
    
    private void ComboIndItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboIndItemStateChanged
        // TODO add your handling code here:
        String Indicacao = ComboInd.getSelectedItem().toString();
        
        filtrar2(Indicacao);
    }//GEN-LAST:event_ComboIndItemStateChanged

    private void ComboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTipoItemStateChanged
        // TODO add your handling code here:
        String tipo = ComboTipo.getSelectedItem().toString();
        
        filtrar(tipo);
    }//GEN-LAST:event_ComboTipoItemStateChanged

    private void ComboIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboIndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboIndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipamentosGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipamentosGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipamentosGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaEquipamentosGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListaEquipamentosGenerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboInd;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JLabel imgHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEq;
    // End of variables declaration//GEN-END:variables
}
