/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;
import backend.Hospital;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import backend.Sistema;
import backend.Serializacao;
import java.util.ArrayList;
import java.util.UUID;


/**
 *
 * 
 */
public class PaginaHospitais extends javax.swing.JFrame {

    DefaultTableModel model; 
    private Sistema sistema;
    private Serializacao bd;
    
    /**
     * 
     * @param sistema
     * @param bd 
     */
    public PaginaHospitais(Sistema sistema, Serializacao bd) {
        initComponents();
        
        model = (DefaultTableModel) tableHospital.getModel();
        this.sistema = sistema;
        this.bd = bd;
        
        carregarTabelaHospital();      
        
    }
    
     public void carregarTabelaHospital()
    {
        model.setRowCount(0);
        ArrayList<Hospital> hospital = sistema.getListaHospital().getListaHospital();
         
        for (int i = 0; i < hospital.size(); i++) {
            
            Hospital hosp = sistema.getListaHospital().getListaHospital().get(i);
            
            if (hosp.getUtiLigado().equals(sistema.getUtilizadorLigado())) {
                 model.addRow(new Object[]{hosp.getIdHospital(), hosp.getNome(), hosp.getLocalidade()});
            }
         }
    }
       
     private void guardarAlteracoes() {
        bd.gravaSistema(sistema);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLimpar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btInserir = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        imgHome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLocalidade = new javax.swing.JTextField();
        btEnfermaria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHospital = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(805, 480));
        setUndecorated(true);
        setSize(new java.awt.Dimension(570, 370));
        getContentPane().setLayout(null);

        btLimpar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(10, 340, 80, 29);

        btEditar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar);
        btEditar.setBounds(10, 240, 80, 29);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Hospitais");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 10, 150, 25);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Nome :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 60, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 80, 120, 30);

        btInserir.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btInserir);
        btInserir.setBounds(10, 190, 80, 29);

        btExcluir.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(10, 290, 80, 29);

        imgHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sydney-opera-house.png"))); // NOI18N
        imgHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHomeMouseClicked(evt);
            }
        });
        getContentPane().add(imgHome);
        imgHome.setBounds(730, 40, 30, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setText("Localidade :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 150, 80, 20);
        getContentPane().add(txtLocalidade);
        txtLocalidade.setBounds(110, 140, 120, 30);

        btEnfermaria.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btEnfermaria.setText("Lista Enfermaria");
        btEnfermaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnfermariaActionPerformed(evt);
            }
        });
        getContentPane().add(btEnfermaria);
        btEnfermaria.setBounds(590, 390, 170, 29);

        tableHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Localidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHospitalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableHospital);
        if (tableHospital.getColumnModel().getColumnCount() > 0) {
            tableHospital.getColumnModel().getColumn(0).setResizable(false);
            tableHospital.getColumnModel().getColumn(1).setResizable(false);
            tableHospital.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 80, 490, 290);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundPRI.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 910, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        // TODO add your handling code here:
        
        String id = UUID.randomUUID().toString();
        
        //Se o hospital tiver o mesmo nome e localidade, já existe
        for (Hospital hospital :  sistema.getListaHospital().getListaHospital() )
        {
            if (hospital.getNome().equals(txtNome.getText()) && (hospital.getLocalidade().equals(txtLocalidade.getText())))
            {
                JOptionPane.showMessageDialog(null,"Esse hospital já existe","Erro",JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        }
        
        //text box nome vazia
        if (txtNome.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Introduza o nome do hospital","Erro",JOptionPane.ERROR_MESSAGE);
             txtNome.requestFocus();
             return;
        }
          
        //text box localidade vazia
        if (txtLocalidade.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Introduza a localidade em que o hospital se encontra","Erro",JOptionPane.ERROR_MESSAGE);
             txtLocalidade.requestFocus();
             return;
        }
        
        //Impede que existam localidades com digitos e caracteres no nome. Exemplo: 123fg4 
        if (txtLocalidade.getText().matches(".*\\d.*")){
             JOptionPane.showMessageDialog(null," Nome da localidade inválido","Erro",JOptionPane.ERROR_MESSAGE);
             txtLocalidade.requestFocus();
             return;
        }
        
        //Impede que existam hospitais com somente numeros no nome ou com digitos e caracteres no nome. Exemplo: 123fg4 
        if (txtNome.getText().matches(".*\\d.*")){
             JOptionPane.showMessageDialog(null," Nome do hospital inválido","Erro",JOptionPane.ERROR_MESSAGE);
             txtNome.requestFocus();
             return;
        }
        
        
        Hospital hospital = new Hospital(sistema.getUtilizadorLigado(),txtNome.getText(), txtLocalidade.getText(), id);
        
        try {
        sistema.getListaHospital().adicionar(hospital);
        JOptionPane.showMessageDialog(null, "Hospital " + txtNome.getText() + " registado!");
        txtNome.setText("");
        txtLocalidade.setText("");
        carregarTabelaHospital();
        }catch(RuntimeException e) {
            //Todas as labels estão preenchidas, no entanto com o tipo de dados errado
            JOptionPane.showMessageDialog(null,"Nome da localidade inválido","Erro",JOptionPane.ERROR_MESSAGE);
        }
        guardarAlteracoes();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:        
        txtNome.setText(null);
        txtLocalidade.setText(null);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
         
        int row = tableHospital.getSelectedRow();
        //ou seja se a linha estiver selecionada

        if(row >= 0){
            model.removeRow(row);
            //remove a linha selecionada
            sistema.getListaHospital().getListaHospital().remove(row);
            carregarTabelaHospital();
            guardarAlteracoes();
            txtNome.setText(null);
            txtLocalidade.setText(null);
            JOptionPane.showMessageDialog(null, "Removido","Informação",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Selecione um hospital","Atenção",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        try {
            int indiceHospital = tableHospital.getSelectedRow();
            Hospital editarHospital = sistema.getListaHospital().getListaHospital().get(indiceHospital);

               if (indiceHospital == -1){
                    JOptionPane.showMessageDialog(null,"Selecione um hospital","Atenção",JOptionPane.WARNING_MESSAGE); 
                    return;       
               }
            
             for (Hospital hospital :  sistema.getListaHospital().getListaHospital() )
        {
            if (hospital.getNome().equals(txtNome.getText()) && (hospital.getLocalidade().equals(txtLocalidade.getText())))
            {
                JOptionPane.showMessageDialog(null,"Esse hospital já existe","Erro",JOptionPane.ERROR_MESSAGE);
                return;
            }
        
        }
        
        if (txtNome.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Introduza o nome do hospital","Erro",JOptionPane.ERROR_MESSAGE);
             txtNome.requestFocus();
             return;
        }
          
        
        if (txtLocalidade.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Introduza a localidade em que o hospital se encontra","Erro",JOptionPane.ERROR_MESSAGE);
             txtLocalidade.requestFocus();
             return;
        }
        
        //Impede que existam localidades com digitos e caracteres no nome. Exemplo: 123fg4 
        if (txtLocalidade.getText().matches(".*\\d.*")){
             JOptionPane.showMessageDialog(null," Nome da localidade inválido","Erro",JOptionPane.ERROR_MESSAGE);
             txtLocalidade.requestFocus();
             return;
        }
        
        //Impede que existam hospitais com somente numeros no nome ou com digitos e caracteres no nome. Exemplo: 123fg4 
        if (txtNome.getText().matches(".*\\d.*")){
             JOptionPane.showMessageDialog(null," Nome do hospital inválido","Erro",JOptionPane.ERROR_MESSAGE);
             txtNome.requestFocus();
             return;
        }
        

            editarHospital.setNome(txtNome.getText());
            editarHospital.setLocalidade(txtLocalidade.getText());
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null,"Selecione um hospital","Atenção",JOptionPane.WARNING_MESSAGE);
            return;
            }
        
        carregarTabelaHospital();
        guardarAlteracoes();
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void imgHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHomeMouseClicked
        // TODO add your handling code here:
        hide();
        PaginaInicialUtilizador paginaInicialUtilizador = new PaginaInicialUtilizador(sistema,bd);
        paginaInicialUtilizador.setLocationRelativeTo(null);
        paginaInicialUtilizador.setVisible(true);
    }//GEN-LAST:event_imgHomeMouseClicked

    private void imgRetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRetrocederMouseClicked
        // TODO add your handling code here:
        hide();
        PaginaInicialUtilizador paginaInicialUtilizador = new PaginaInicialUtilizador(sistema,bd);
        paginaInicialUtilizador.setLocationRelativeTo(null);
        paginaInicialUtilizador.setVisible(true);
    }//GEN-LAST:event_imgRetrocederMouseClicked

    private void btEnfermariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnfermariaActionPerformed
        // TODO add your handling code here:
              
        int indiceHospital = tableHospital.getSelectedRow();    //abre a janela que cria as tarefas de um projeto
                                                    //selecionado da tabela
        if (indiceHospital == -1){
            
              JOptionPane.showMessageDialog(null,"Selecione um hospital","Atenção",JOptionPane.WARNING_MESSAGE); 
        }  else {             
        
        PaginaEnfermarias enf = new PaginaEnfermarias(sistema, bd, indiceHospital);
        guardarAlteracoes();
        dispose();
        enf.setVisible(true);
        enf.setLocationRelativeTo(null);
        }
        
       /* int rowIndex = table.getSelectedRow();
        String ID = (String) table.getValueAt(rowIndex, 0);
        //Caso o ID não seja nulo
        if(!ID.equals("")){
            Hospital hospital = new Hospital();
            hospital.setUtiLigado(sistema.getUtilizadorLigado());
            hospital.setNome(table.getValueAt(rowIndex, 1).toString());
            hospital.setLocalidade(table.getValueAt(rowIndex, 2).toString());
            hospital.setId_Hospital(table.getValueAt(rowIndex, 0).toString());
        //A linha que está selecionada vai definir o hospital com esse ID, o hospital selecionado
        //Assim a enfermaria que criar vai estar associada ao hospital seguinte
        //sistema.setHospitalSelecionado(sistema.getListaHospital().getHospital(ID));
        sistema.setHospitalSelecionado(hospital);
        guardarAlteracoes();
        dispose();
        ListaEnfermarias en = new ListaEnfermarias(sistema, bd);
        en.setVisible(true);  
        } else {
        JOptionPane.showMessageDialog(null,"Hospital não encontrado!","Erro",JOptionPane.ERROR_MESSAGE);    
        }*/  
    }//GEN-LAST:event_btEnfermariaActionPerformed

    private void tableHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHospitalMouseClicked
        // TODO add your handling code here:
         int indiceHospital = tableHospital.getSelectedRow();  //quando o utilizador seleciona um hospital clicando
                                                  //na tabela

        if(indiceHospital>=0 && indiceHospital < sistema.getListaHospital().getListaHospital().size()) {
            
            Hospital hospital = sistema.getListaHospital().getListaHospital().get(indiceHospital);
            txtNome.setText(hospital.getNome());
            txtLocalidade.setText(hospital.getLocalidade());
        }
            
       /* if (evt.getClickCount() == 2){
        int rowIndex = table.getSelectedRow();
        String ID = (String) table.getValueAt(rowIndex, 0);
        if(!ID.equals("")){
        sistema.setHospitalSelecionado(sistema.getListaHospital().getHospital(ID));
        guardarAlteracoes();
        dispose();
        ListaEnfermarias en = new ListaEnfermarias(sistema, bd);
        en.setVisible(true);  
        } else {
        JOptionPane.showMessageDialog(null,"Hospital não encontrado!","Erro",JOptionPane.ERROR_MESSAGE);    
        }
    }
        if (evt.getClickCount() == 1) {
        int rowIndex = table.getSelectedRow();
        txtCodigo.setText(table.getValueAt(rowIndex, 0).toString());
        txtNome.setText(table.getValueAt(rowIndex, 1).toString());
        txtLocalidade.setText(table.getValueAt(rowIndex, 2).toString());
        //txtCodigo.setEnabled(false);
        }*/
    }//GEN-LAST:event_tableHospitalMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaHospitais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaHospitais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaHospitais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaHospitais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ListaHospitais(sistema,bd).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEnfermaria;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel imgHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableHospital;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
